sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: 王元旭的世界
name: 王元旭
description: 一个人的命运啊，当然要靠自我奋斗，但是也要考虑历史的进程

show_excerpt: true

twitter: https://twitter.com/maoli_nb
email: mailto:wangyuanxu0916@qq.com
github: https://github.com/mao-li
rss: true



site_statistics: true

cnzz_id:

baidu_id:

google_id:
copy_with_declaration: true
reward: false
# reward_description: 如果你觉得本文对你有帮助，不妨请我喝杯咖啡

theme: jekyll-theme-minimal

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
